server {
    listen 80 default_server;
    server_name _;

    client_max_body_size 512m;
    root /usr/share/nginx/html;
    index index.html;

    location = /runtime-config.json {
        add_header Cache-Control "no-store";
        try_files $uri =404;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
