model:
  providers:
    seedream:
      api_key: ''
    deepseek:
      api_key: ''
    seedance:
      api_key: ''
    openai:
      api_key: ''
    ark:
      api_key: ''
    volcengine:
      api_key: ''
