spring:
  application:
    name: JianDou Spring API
  datasource:
    url: ${JIANDOU_DATABASE_URL:jdbc:mysql://127.0.0.1:3306/jiandou?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai}
    username: ${JIANDOU_DATABASE_USER:root}
    password: ${JIANDOU_DATABASE_PASSWORD:root}
    driver-class-name: ${JIANDOU_DB_DRIVER:com.mysql.cj.jdbc.Driver}

server:
  port: ${SERVER_PORT:8000}
  error:
    include-message: always

logging:
  level:
    root: INFO
    com.jiandou.api: INFO
