from __future__ import annotations

from sqlalchemy import Column, Float, Integer, String, Text

from app.database import Base


class BizTask(Base):
    __tablename__ = "biz_tasks"

    task_id = Column(String(64), primary_key=True)
    owner_user_id = Column(Integer, nullable=False)
    task_type = Column(String(64), nullable=False)
    title = Column(String(255), nullable=False, default="")
    description = Column(Text, nullable=True)
    aspect_ratio = Column(String(32), nullable=True)
    min_duration_seconds = Column(Integer, nullable=True)
    max_duration_seconds = Column(Integer, nullable=True)
    output_count = Column(Integer, nullable=True)
    source_primary_asset_id = Column(String(64), nullable=True)
    source_file_name = Column(String(255), nullable=True)
    source_asset_ids_json = Column(Text, nullable=True)
    source_file_names_json = Column(Text, nullable=True)
    request_payload_json = Column(Text, nullable=True)
    context_json = Column(Text, nullable=True)
    intro_template = Column(Text, nullable=True)
    outro_template = Column(Text, nullable=True)
    creative_prompt = Column(Text, nullable=True)
    task_seed = Column(Integer, nullable=True)
    effect_rating = Column(Integer, nullable=True)
    effect_rating_note = Column(Text, nullable=True)
    rated_at = Column(String(32), nullable=True)
    model_provider = Column(String(64), nullable=True)
    execution_mode = Column(String(32), nullable=True)
    editing_mode = Column(String(32), nullable=True)
    status = Column(String(32), nullable=False)
    progress = Column(Integer, nullable=True)
    error_code = Column(String(64), nullable=True)
    error_message = Column(Text, nullable=True)
    plan_json = Column(Text, nullable=True)
    retry_count = Column(Integer, default=0)
    timezone_offset_minutes = Column(Integer, nullable=True)
    started_at = Column(String(32), nullable=True)
    finished_at = Column(String(32), nullable=True)
    create_time = Column(String(32), default=None)
    update_time = Column(String(32), default=None)
    is_deleted = Column(Integer, default=0)


class BizTaskStatusHistory(Base):
    __tablename__ = "biz_task_status_history"

    task_status_history_id = Column(String(64), primary_key=True)
    task_id = Column(String(64), nullable=False)
    previous_status = Column(String(32), nullable=True)
    current_status = Column(String(32), nullable=False)
    progress = Column(Integer, nullable=True)
    stage = Column(String(64), nullable=True)
    event = Column(String(64), nullable=True)
    message = Column(Text, nullable=True)
    payload_json = Column(Text, nullable=True)
    change_time = Column(String(32), nullable=True)
    operator_type = Column(String(32), nullable=True)
    operator_id = Column(String(64), nullable=True)
    timezone_offset_minutes = Column(Integer, nullable=True)
    create_time = Column(String(32), default=None)
    update_time = Column(String(32), default=None)
    is_deleted = Column(Integer, default=0)


class BizTaskAttempt(Base):
    __tablename__ = "biz_task_attempts"

    task_attempt_id = Column(String(64), primary_key=True)
    task_id = Column(String(64), nullable=False)
    attempt_no = Column(Integer, nullable=False)
    trigger_type = Column(String(32), nullable=True)
    status = Column(String(32), nullable=False)
    queue_name = Column(String(64), nullable=True)
    worker_instance_id = Column(String(64), nullable=True)
    queue_entered_at = Column(String(32), nullable=True)
    queue_left_at = Column(String(32), nullable=True)
    claimed_at = Column(String(32), nullable=True)
    started_at = Column(String(32), nullable=True)
    finished_at = Column(String(32), nullable=True)
    resume_from_stage = Column(String(64), nullable=True)
    resume_from_clip_index = Column(Integer, nullable=True)
    failure_code = Column(String(64), nullable=True)
    failure_message = Column(Text, nullable=True)
    payload_json = Column(Text, nullable=True)
    timezone_offset_minutes = Column(Integer, nullable=True)
    create_time = Column(String(32), default=None)
    update_time = Column(String(32), default=None)
    is_deleted = Column(Integer, default=0)


class BizTaskStageRun(Base):
    __tablename__ = "biz_task_stage_runs"

    task_stage_run_id = Column(String(64), primary_key=True)
    task_id = Column(String(64), nullable=False)
    attempt_id = Column(String(64), nullable=True)
    stage_name = Column(String(64), nullable=False)
    stage_seq = Column(Integer, nullable=True)
    clip_index = Column(Integer, nullable=True)
    status = Column(String(32), nullable=False)
    worker_instance_id = Column(String(64), nullable=True)
    started_at = Column(String(32), nullable=True)
    finished_at = Column(String(32), nullable=True)
    duration_ms = Column(Integer, nullable=True)
    input_summary_json = Column(Text, nullable=True)
    output_summary_json = Column(Text, nullable=True)
    error_code = Column(String(64), nullable=True)
    error_message = Column(Text, nullable=True)
    timezone_offset_minutes = Column(Integer, nullable=True)
    create_time = Column(String(32), default=None)
    update_time = Column(String(32), default=None)
    is_deleted = Column(Integer, default=0)


class BizTaskQueueEvent(Base):
    __tablename__ = "biz_task_queue_events"

    task_queue_event_id = Column(String(64), primary_key=True)
    task_id = Column(String(64), nullable=False)
    attempt_id = Column(String(64), nullable=True)
    queue_name = Column(String(64), nullable=True)
    event_type = Column(String(32), nullable=False)
    worker_instance_id = Column(String(64), nullable=True)
    queue_position_hint = Column(Integer, nullable=True)
    payload_json = Column(Text, nullable=True)
    event_time = Column(String(32), nullable=True)
    timezone_offset_minutes = Column(Integer, nullable=True)
    create_time = Column(String(32), default=None)
    update_time = Column(String(32), default=None)
    is_deleted = Column(Integer, default=0)


class BizWorkerInstance(Base):
    __tablename__ = "biz_worker_instances"

    worker_instance_id = Column(String(64), primary_key=True)
    worker_type = Column(String(64), nullable=False)
    queue_name = Column(String(64), nullable=True)
    host_name = Column(String(255), nullable=True)
    process_id = Column(Integer, nullable=True)
    status = Column(String(32), nullable=False)
    started_at = Column(String(32), nullable=True)
    last_heartbeat_at = Column(String(32), nullable=True)
    stopped_at = Column(String(32), nullable=True)
    metadata_json = Column(Text, nullable=True)
    timezone_offset_minutes = Column(Integer, nullable=True)
    create_time = Column(String(32), default=None)
    update_time = Column(String(32), default=None)
    is_deleted = Column(Integer, default=0)


class BizTaskModelCall(Base):
    __tablename__ = "biz_task_model_calls"

    task_model_call_id = Column(String(64), primary_key=True)
    task_id = Column(String(64), nullable=False)
    call_kind = Column(String(32), nullable=True)
    stage = Column(String(64), nullable=True)
    operation = Column(String(64), nullable=True)
    provider = Column(String(64), nullable=True)
    provider_model = Column(String(128), nullable=True)
    requested_model = Column(String(128), nullable=True)
    resolved_model = Column(String(128), nullable=True)
    model_name = Column(String(128), nullable=True)
    model_alias = Column(String(128), nullable=True)
    endpoint_host = Column(String(255), nullable=True)
    request_id = Column(String(64), nullable=True)
    request_payload_json = Column(Text, nullable=True)
    response_payload_json = Column(Text, nullable=True)
    http_status = Column(Integer, nullable=True)
    response_status_code = Column(Integer, nullable=True)
    success = Column(Integer, nullable=True)
    error_code = Column(String(64), nullable=True)
    error_message = Column(Text, nullable=True)
    latency_ms = Column(Integer, nullable=True)
    duration_ms = Column(Integer, nullable=True)
    input_tokens = Column(Integer, nullable=True)
    output_tokens = Column(Integer, nullable=True)
    started_at = Column(String(32), nullable=True)
    finished_at = Column(String(32), nullable=True)
    timezone_offset_minutes = Column(Integer, nullable=True)
    create_time = Column(String(32), default=None)
    update_time = Column(String(32), default=None)
    is_deleted = Column(Integer, default=0)


class BizTaskResult(Base):
    __tablename__ = "biz_task_results"

    task_result_id = Column(String(64), primary_key=True)
    task_id = Column(String(64), nullable=False)
    result_type = Column(String(32), nullable=False)
    clip_index = Column(Integer, nullable=True)
    title = Column(String(255), nullable=True)
    reason = Column(Text, nullable=True)
    source_model_call_id = Column(String(64), nullable=True)
    material_asset_id = Column(String(64), nullable=True)
    start_seconds = Column(Float, nullable=True)
    end_seconds = Column(Float, nullable=True)
    duration_seconds = Column(Float, nullable=True)
    preview_path = Column(String(512), nullable=True)
    download_path = Column(String(512), nullable=True)
    width = Column(Integer, nullable=True)
    height = Column(Integer, nullable=True)
    mime_type = Column(String(64), nullable=True)
    size_bytes = Column(Integer, nullable=True)
    remote_url = Column(String(1024), nullable=True)
    extra_json = Column(Text, nullable=True)
    produced_at = Column(String(32), nullable=True)
    timezone_offset_minutes = Column(Integer, nullable=True)
    create_time = Column(String(32), default=None)
    update_time = Column(String(32), default=None)
    is_deleted = Column(Integer, default=0)


class BizMaterialAsset(Base):
    __tablename__ = "biz_material_assets"

    id = Column(Integer, primary_key=True, autoincrement=True)
    material_asset_id = Column(String(64), nullable=False, unique=True)
    owner_user_id = Column(Integer, nullable=False)
    task_id = Column(String(64), nullable=True)
    workflow_id = Column(String(64), nullable=True)
    source_task_id = Column(String(64), nullable=True)
    source_material_id = Column(String(64), nullable=True)
    asset_role = Column(String(32), nullable=True)
    stage_type = Column(String(64), nullable=True)
    clip_index = Column(Integer, nullable=True)
    version_no = Column(Integer, nullable=True)
    selected_for_next = Column(Integer, default=0)
    user_rating = Column(Integer, nullable=True)
    rating_note = Column(Text, nullable=True)
    media_type = Column(String(32), nullable=True)
    title = Column(String(255), nullable=True)
    origin_provider = Column(String(64), nullable=True)
    origin_model = Column(String(128), nullable=True)
    remote_task_id = Column(String(64), nullable=True)
    remote_asset_id = Column(String(64), nullable=True)
    original_file_name = Column(String(255), nullable=True)
    stored_file_name = Column(String(255), nullable=True)
    file_ext = Column(String(32), nullable=True)
    storage_provider = Column(String(64), nullable=True)
    mime_type = Column(String(64), nullable=True)
    size_bytes = Column(Integer, nullable=True)
    sha256 = Column(String(64), nullable=True)
    duration_seconds = Column(Float, nullable=True)
    width = Column(Integer, nullable=True)
    height = Column(Integer, nullable=True)
    has_audio = Column(Integer, default=0)
    local_storage_path = Column(String(512), nullable=True)
    local_file_path = Column(String(512), nullable=True)
    public_url = Column(String(1024), nullable=True)
    thumbnail_url = Column(String(1024), nullable=True)
    third_party_url = Column(String(1024), nullable=True)
    remote_url = Column(String(1024), nullable=True)
    metadata_json = Column(Text, nullable=True)
    captured_at = Column(String(32), nullable=True)
    timezone_offset_minutes = Column(Integer, nullable=True)
    create_time = Column(String(32), default=None)
    update_time = Column(String(32), default=None)
    is_deleted = Column(Integer, default=0)


